stages:
    - build

image: ubuntu:bionic

build:
    stage: build
    before_script:
        - apt update
        - apt install -y zip curl unzip
        - curl -LO https://raw.github.com/robertpeteuil/terraform-installer/master/terraform-install.sh
        - chmod +x terraform-install.sh
        - ./terraform-install.sh
        - terraform init
    script:
        - echo $CONFIG > src/config.py
        - bash build.sh
        - terraform apply -auto-approve -var 'accountId=$AWS_ACCOUNT_ID'
    only:
        - master

